SMS/Controllers/SubjectController.cs
/// <summary>
///
/// </summary>
/// <author>Shajanthan</author>

using SMS_BL.Subject;
using SMS_ViewModels.Subject;
using System.Linq;
using System;
using System.Web.Mvc;
using System.Collections.Generic;
using SMS_Models.Subject;
using SMS_BL.Subject.Interface;
using SMS_Data;

namespace SMS.Controllers
{
    public class SubjectController : Controller
    {

        //private readonly SubjectBL _subjectBL = new SubjectBL();

        private readonly ISubjectRepository _subjectRepository;

        public SubjectController()
        {
            _subjectRepository = new SubjectRepository(new SMS_DBEntities());
        }

        // GET: Subject
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Add Subject
        /// </summary>
        /// <param name="pageNumber"></param>
        /// <param name="pageSize"></param>
        /// <param name="isActive"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AllSubjects(int pageNumber, int pageSize, bool? isActive = null)
        {
            var subjectResult = new SubjectViewModel();

            //subjectResult.SubjectList = _subjectBL.GetAllSubject(isActive);

            subjectResult.SubjectList = _subjectRepository.GetAllSubject(isActive);

            List<SubjectBO> pageData;
            int totalPage;
            Pagination(pageNumber, pageSize, subjectResult, out pageData, out totalPage);

            if (pageData.Count > 0)
            {
                return Json(new { success = true, data = pageData, totalPages = totalPage }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = "No Data Found", totalPages = totalPage }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// For pagination
        /// </summary>
        /// <param name="pageNumber"></param>
        /// <param name="pageSize"></param>
        /// <param name="subjectResult"></param>
        /// <param name="pageData"></param>
        /// <param name="totalPage"></param>
        private static void Pagination(int pageNumber, int pageSize, SubjectViewModel subjectResult, out List<SubjectBO> pageData, out int totalPage)
        {
            int skip = (pageNumber - 1) * pageSize;


            pageData = subjectResult.SubjectList.OrderBy(s => s.SubjectID).Skip(skip).Take(pageSize).ToList();
            double totalRecords = subjectResult.SubjectList.Count();
            double pagesize = pageSize;

            double totalPages = Math.Ceiling(totalRecords / pageSize);

            totalPage = (int)Math.Round(totalPages);
        }

        /// <summary>
        /// Delete Subject
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteSubject(int id)
        {
            var msg = "";
            try
            {
                //bool deleteSubject = _subjectBL.DeleteSubject(id,out msg);

                bool deleteSubject = _subjectRepository.DeleteSubject(id, out msg);

                return Json(new { success = deleteSubject, msg});
            }
            catch
            {
                return Json(new { success = false, msg });
            }
        }

        /// <summary>
        /// Get Subject
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult AddSubject(long id=0)
        {
            if (id == 0) {
                return PartialView("_AddSubject",new SubjectBO());
            }
            //var subject=_subjectBL.GetSubjetByID(id);
            var subject = _subjectRepository.GetSubjetByID(id);
            return PartialView("_AddSubject", subject);

        }


        /// <summary>
        /// Add Subjects
        /// </summary>
        /// <param name="subject"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSubject(SubjectBO subject)
        {
            var msg = "";
            if (ModelState.IsValid)
            {
                try
                {
                    //bool isSaveSuccess = _subjectBL.SaveSubject(subject, out msg);
                    bool isSaveSuccess = _subjectRepository.SaveSubject(subject, out msg);

                    return Json(new { success = isSaveSuccess, message = msg });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, message = "Error occurred while adding the subject: " + ex.Message });
                }
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors)
                                              .Select(e => e.ErrorMessage)
                                              .ToList();
                return Json(new { success = false, message = "Please fill all details.", errors = errors });
            }
        }

        /// <summary>
        /// Subject_code Validation json result
        /// </summary>
        /// <param name="subCode"></param>
        /// <returns></returns>
        public JsonResult IsSubCodeAvailable(string subCode)
        {
            //bool isAvailable = _subjectBL.CheckSubCode(subCode);
            bool isAvailable = _subjectRepository.CheckSubCode(subCode);
            return Json(isAvailable, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Subject_Name Validation jason result
        /// </summary>
        /// <param name="subName"></param>
        /// <returns></returns>
        public JsonResult IsSubNameAvailable(string subName)
        {
            //bool isAvailable = _subjectBL.CheckSubname(subName);
            bool isAvailable = _subjectRepository.CheckSubname(subName);
            return Json(isAvailable, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Toggle Subject Avaliable
        /// </summary>
        /// <param name="id"></param>
        /// <param name="enable"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ToggleEnable(int id, bool enable)
        {
            var msg = "";
            try
            {
                //bool isToggle = _subjectBL.ToggleSubject(id, enable, out msg);
                bool isToggle = _subjectRepository.ToggleSubject(id, enable, out msg);

                return Json(new { success = isToggle, message = msg });
            }
            catch
            {
                return Json(new { success = false, message = "An error occurred" });
            }
        }

        /// <summary>
        /// Search Subject
        /// </summary>
        /// <param name="searchTerm"></param>
        /// <param name="searchCriteria"></param>
        /// <returns></returns>
        public ActionResult Search(string searchTerm, string searchCriteria)
        {
            //var subjects = _subjectBL.SearchSubject(searchTerm, searchCriteria).ToList();

            var subjects = _subjectRepository.SearchSubject(searchTerm, searchCriteria).ToList();

            if (subjects.Count > 0)
            {
                return PartialView("_SubjectTable", subjects);
            }
            else
            {
                return PartialView("_SubjectTable", null);
            }
        }

        /// <summary>
        /// check the subject is allocated or not
        /// </summary>
        /// <param name="subjectID"></param>
        /// <returns></returns>
        public JsonResult IsSubjectAllocated(long subjectID)
        {
            bool isAllocated = _subjectRepository.IsSubjectInUse(subjectID);
            return Json(isAllocated, JsonRequestBehavior.AllowGet);
        }




    }
}

SMS/Views/Subject/Index.cshtml
@model SMS_ViewModels.Subject.SubjectViewModel
@{
    ViewBag.Title = "Subjects";
}


<div class="container-fluid layout">
    <div class="panel panel-default">
        <div class="panel-heading">
            <!--Heading-->
            <div class="text-uppercase headings">
                <h2>Subjects</h2>
            </div>
            <!--search add section-->
            <div class="container-fluid m-2 crudLayoud " id="subjectHead">
                <div class="row justify-content-between align-items-center d-flex flex-wrap">
                    <!-- add btn-->
                    <div class="col-lg-2 col-md-6 mb-2 mb-md-0">
                        <button id="addNew" class="btn">+ Add New Subject</button>
                    </div>
                    <!--search section-->
                    <div class="col-lg-6 col-md-5 d-flex flex-wrap justify-content-between">
                        <div class="d-flex" id="dataLimit">
                            <label class="col-form-label">Filter </label>
                            <select id="pageSize" class="form-select flex-grow-1">
                                <option value="5" selected>5</option>
                                <option value="10">10</option>
                                <option value="15">15</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                            </select>
                        </div>
                        <div class="d-flex">
                            <label for="isActiveFilter" class="col-form-label">Status: </label>
                            <select class="form-select flex-grow-1" id="isActiveFilter">
                                <option value="">All</option>
                                <option value="true">Active</option>
                                <option value="false">Inactive</option>
                            </select>
                        </div>
                        <div class="d-flex">
                            <div class="input-group">
                                <select class="form-select" id="searchCriteria">
                                    <option value="" selected>All</option>
                                    <option value="SubjectCode">Subject Code</option>
                                    <option value="Name">Name</option>
                                </select>
                            </div>
                            <input type="text" id="searchInput" class="form-control" placeholder="Search...">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Table Display data-->
        <div class="panel-body">
            <div class="table-responsive">
                <table id="subjectDetails" class="table table-bordered table-striped">
                    <thead class="tableheading text-center">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.SubjectList.First().IsEnable)</th>
                            <th class="sortable">@Html.DisplayNameFor(model => model.SubjectList.First().SubjectCode)</th>
                            <th class="sortable">@Html.DisplayNameFor(model => model.SubjectList.First().Name)</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody class="text-center" id="tableBody"></tbody>
                </table>
                <div class="container-fluid w-100" id="paginationNextPrevious">
                    <ul class="pagination justify-content-center">
                        <li class="page-item">
                            <button id="prevButton" class="btn btn-outline-primary page-button" aria-label="Previous" onclick="previousData()">
                                <span aria-hidden="true"><i class="bi bi-chevron-left"></i></span>
                            </button>
                        </li>

                        <li class="page-item">
                            <button id="nextButton" class="btn btn-outline-primary page-button" aria-label="Next" onclick="nextData()">
                                <span aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                            </button>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <!--Partial View section-->
    <div class="partialLayout">
        <div class="container-fluid" style="display:none" id="addSubjectForm">
            @*@Html.Partial("_AddSubject")*@
        </div>
    </div>

</div>


@section Scripts{

   <script src="~/SMS_Scripts/Subject/Subject.js"></script>

}

SMS/Views/Subject/_AddSubject.cshtml
@model SMS_Models.Subject.SubjectBO


@using (Ajax.BeginForm("AddSubject", "Subject", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "addSubjectSuccess",
    OnFailure = "addSubjectFailure"
}, new { @class = "border p-4 mx-auto Customform", style = "max-width: 500px;" }))
{
    
    
    @Html.HiddenFor(model => model.SubjectID)
   

    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="justify-content-center align-items-center">

        <div class="form-group row m-2">
            <div class="col-md-4">

                @Html.LabelFor(model => model.SubjectCode, htmlAttributes: new { @class = "col-form-label", style = "word-wrap: break-word;" })<span class="required-asterisk">*</span>
            </div>
            <div class="col-md-8 ">

                @Html.EditorFor(model => model.SubjectCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Subject Code", id = "SubjectCode" } })
                <span id="SubjectCode-error" class="text-danger"></span>
                @Html.ValidationMessageFor(model => model.SubjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row m-2">
            <div class="col-md-4">

                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-form-label", style = "word-wrap: break-word;" })<span class="required-asterisk">*</span>
            </div>
            <div class="col-md-8">

                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Subject Name", id = "SubjectName" } })
                <span id="SubjectName-error" class="text-danger"></span>
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row m-2">
            <div class="col-md-4">

                @Html.LabelFor(model => model.IsEnable, htmlAttributes: new { @class = "col-form-label" })
            </div>
            <div class="col-md-8">

                <div class="form-check m-3">
                    @Html.CheckBoxFor(model => model.IsEnable, new { @class = "form-check-input", id = "Enable" })
                </div>
            </div>
        </div>

        <div class="form-group row m-2">
            <div class="col-md-10 offset-md-4">
                <br />
                <input type="submit" value="@((Model.SubjectID==0 ? "Create" : "Update"))" class="btn btn-primary" />
                <a href="#" class="btn btn-secondary" onclick="backSubject()">Back</a>
            </div>
        </div>
    </div>

    <script>

        //SubjectCode Validation
        $('#SubjectCode').change(function () {
            var subCode = $(this).val();
            $.ajax({
                url: '/Subject/IsSubCodeAvailable',
                type: 'GET',
                data: { subCode: subCode },
                success: function (response) {
                    $('#SubjectCode-error').text(response ? '' : 'Subject code already exists.');
                }
            });
        });

        //SubjectName Validation
        $('#SubjectName').change(function () {
            var subName = $(this).val();
            $.ajax({
                url: '/Subject/IsSubNameAvailable',
                type: 'GET',
                data: { subName: subName },
                success: function (response) {
                    $('#SubjectName-error').text(response ? '' : 'Subject Name already exists.');
                }
            });
        });
    </script>
}

SMS/Views/Subject/_SubjectTable.cshtml
@if (Model != null)
{
    foreach (var subject in Model)
    {
        <tr>
            <td>
                @if (subject.IsEnable)
                {
                    <button type="button" class="btn btn-success btn-sm" onclick="toggleEnable('@subject.SubjectID', false,'@subject.Name')"> <i class="btn-success bi bi-power" style="filter: grayscale(100%)"></i></button>
                }
                else
                {
                    <button type="button" class="btn btn-danger btn-sm" onclick="toggleEnable('@subject.SubjectID', false,'@subject.Name')"> <i class="btn-success bi bi-power" style="filter: grayscale(100%)"></i></button>
                }
            </td>
            <td>@subject.SubjectCode</td>
            <td>@subject.Name</td>
            <td>
                <button type="button" class="btn btn-sm btn-primary" id="editBtn_@subject.SubjectID" onclick="editSubject('@subject.SubjectID')"><i class="bi bi-pen small-icons"></i></button>
                <button type="button" class="btn btn-sm btn-danger" id="deleteBtn_@subject.SubjectID" onclick="deleteSubject('@subject.SubjectID',false,'@subject.Name')"><i class="bi bi-trash small-icons"></i></button>
                <span id="badge_@subject.SubjectID" class='badge bg-primary'>Allocated</span>
            </td>
        </tr>
        <script>
            $.ajax({
              //check the subject is allocated or not
              url: '/Subject/IsSubjectAllocated',
              type: 'GET',
              data: { subjectID: '@subject.SubjectID' },
              success: function (response) {
                  if (response) {
                      $('#editBtn_@subject.SubjectID, #deleteBtn_@subject.SubjectID').hide();
                      $('#badge_@subject.SubjectID').show();
                  }
                  else
                  {
                      //$('#editBtn_@subject.SubjectID, #deleteBtn_@subject.SubjectID').prop('disabled', false);
                      $('#badge_@subject.SubjectID').hide();
                  }
              }
          });
        </script>
    }
}
else
{
    <tr>
        <td colspan="4">No data found</td>
    </tr>
}